### ISSUE TITLE
Improve guide importing script

### ISSUE THREAD

**Issue by locks** [ember-learn/guias#1]
I'm currently rendering markdown for each guide, but that leads to a sslliigghhtt problem, which is only having access to the latest version's markdown. I'd like not to incur the extra processing of rendering a markdown, so I'm thinking of rendering HTML instead.

But for that I need a script to extract the necessary HTML and upload to couchdb.

https://github.com/mswanson/ember-guides-markdown/blob/master/lib/import_version.rb here's a first version
https://github.com/emberjs/guides.emberjs.com/tree/master/snapshots here's the files to extract from

There's a slight problem that < v2.2.0 the HTML is different. Relevant sections:
- https://github.com/emberjs/guides.emberjs.com/blob/master/snapshots/v2.1.0/addons-and-dependencies/managing-dependencies/index.html#L72
- https://github.com/emberjs/guides.emberjs.com/blob/master/snapshots/v2.4.0/addons-and-dependencies/managing-dependencies/index.html#L85
## CouchDB document

Naming scheme: `guide-${language}-vx.x.x-${section}-${guide}`, being `language` in the `[a-z]{2}-[A-Z]{2}` format, and `section` and `guide` hyphenized if multi-word.

Keys: `type`, `language`, `version`, `section`, `guide`, `title`, `html`

Example:

```
{
   "_id": "guide-en-US-v2.3.0-addons-and-dependencies-managing-dependencies",
   "_rev": "1-8d2e9fd06b2260bed20e649931f70c7f",
   "type": "guide",
   "version": "v2.3.0",
   "section": "addons-and-dependencies",
   "guide": "managing-dependencies",
   "title": "Managing Dependencies",
   "language": "en-US",
   "html": "…"
}
```

**Comment by knownasilya** [comment]
Script is here https://gist.github.com/locks/c5553ecb613f71d816c1b857f4e9863d

**Comment by knownasilya** [comment]
I wrote a script that scrapes the TOC, https://github.com/knownasilya/pull-tocs just need to add the couch push, and maybe It should also pull the guides and fix the ids at the same time.

**Comment by dweremeichik** [comment]
Since you are using ember-pouch, your database docs will need to look a little different, see [this](https://github.com/nolanlawson/ember-pouch/issues/155).

**Comment by knownasilya** [comment]
On that note, how would I use the relational ids feature?

**Comment by dweremeichik** [comment]
Currently you use `"type": "guide"` to split up your doc types, ember pouch uses the id for this. The id is based on the model name, for example, if you had a model named "guide" an id for that might be "guide_2_07c7bed0d16968d166a6343deb6ac315"

See the following links:
- [Id format](https://github.com/nolanlawson/relational-pouch/issues/60)

- [Transforming your current data](https://github.com/nolanlawson/ember-pouch/issues/53)
