### ISSUE TITLE
Keep guide open on version switch

### ISSUE THREAD

**Issue by knownasilya** [ember-learn/guias#7]
Currently when changing versions the guide changes to the static "index"
page. If another guide is selected and it exists for that version it should go there instead.

**Comment by locks** [comment]
I'd like to try to be a little more clever with the final solution:

- Check if section+guide exists, transition
- Check if guide exists, transition
- Check if section exists, transition

**Comment by knownasilya** [comment]
How do you transition to a guide by itself?
Also if transitioning to a section, would that open the first guide in that section?

**Comment by locks** [comment]
> How do you transition to a guide by itself?
The guide document has the section it belongs to, so you can use that for transitioning

> Also if transitioning to a section, would that open the first guide in that section?
Yup!
